name: cctquake
description: "A new Flutter project."

version: 15.0.0+15


environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  curved_navigation_bar: ^1.0.1
  onesignal_flutter: ^5.2.9
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  shared_preferences: ^2.4.0
  fl_chart: ^0.70.2
  device_info_plus: ^11.2.2
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  syncfusion_flutter_datepicker: ^28.2.6
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_screenutil: ^5.9.0
  printing: ^5.6.0
  flip_card: ^0.6.0
  mailer: ^6.4.1

  

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^2.4.10  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/CCTQuakeAlert_logo.jpg"
  min_sdk_android: 24
  android_adaptive_icon: true
  android_foreground: "images/logo CCTQuake_.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/video/Tutorial.mp4
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans_18pt-SemiBold.ttf
    - family: LibreFranklin
      fonts:
        - asset: fonts/LibreFranklin-Medium.ttf

